### ISSUE TITLE
Episode filter expressed like a two-number part

### ISSUE THREAD

**Issue by jy95** [clement-escolano/parse-torrent-title#12]
Hello,

I checked the [test ](https://github.com/clement-escolano/parse-torrent-title/blob/master/test/episode.js) file and I discover a common case that isn't covered : When the episode number is expressed like a two number part (example: `01` , `12` , etc) after the title

Demo time : 
``` js
const nameParser = require('parse-torrent-title');
var title = "Assassination Classroom 01 Vostfr.mp4";
var json = nameParser.parse(title);
console.log(json);
```

result :

``` js
{ "container": "mp4" , "language": "vostfr" , "title": "Assassination Classroom 01" }
```

expected ; 
``` js
{ "container": "mp4" , "language": "vostfr" , "title": "Assassination Classroom", "episode": 1 }
```
Any ideas how to solve it ? Here is a tap test to help you

```js
it("should return the title", () => {
        const releaseName = "Assassination Classroom 01 Vostfr";
        expect(parse(releaseName)).to.deep.include({ episode: 1 });
    });
```

Thanks.

Edit: My current idea to do that is to do a second extraction on the `title` property after the other are done (with a option param like this [project](https://www.npmjs.com/package/scene-release-parser)). For example : 

``` js
const nameParser = require('parse-torrent-title');
// Options
const options = {
     extractEpisodeNumberFromTitle: true // force extract of the episode number inside the title property (in the end) 
}
// Demo time
var title = "Assassination Classroom 01 Vostfr.mp4";
var json = nameParser.parse(title, options);
// the result (json)
{ "container": "mp4" , "language": "vostfr" , "title": "Assassination Classroom", "episode": 1 }
```

So the current code inside parser.js after line 97 can become : 

```js
parse(title,options={}) {
        const result = {};
        let endOfTitle = title.length;

        for (const handler of this.handlers) {
            const matchIndex = handler({ title, result });
            if (matchIndex && matchIndex < endOfTitle) {
                endOfTitle = matchIndex;
            }
        }

        result.title = cleanTitle(title.substr(0, endOfTitle));
        
        if (options.extractEpisodeNumberFromTitle === true) {
            // The regex to do that could be this :
            let regexEpisodeNumber = /^([\s\w]+)\s([0-9]{1,2})$/;
            // extract the parts and set the episode and title properties
        }
        
        return result;
    }
```

**Comment by jy95** [comment]
I close this issue : For some files like the IMDB shows, [number in title (sometimes/often to the end) ](http://www.imdb.com/list/ls054203065/) could be a disavantage.

In my rewritten [package](https://github.com/jy95/mediaScan), I prefer to give the choice to the final user with a parser custom option ...

**Comment by clement-escolano** [comment]
Indeed, it might create some problems with other movies 😢
Perfect with the option 😉
