### ISSUE TITLE
Can't extend ParserResult interface in TypeScript

### ISSUE THREAD

**Issue by lucafaggianelli** [clement-escolano/parse-torrent-title#14]
I extended the parser with a `part` property, that is:
```ts
const result = ptt.addHandler('part', /(?:Part|CD)[. ]?([0-9])/i, { type: 'integer' })
```

but in TypeScript I can't retrieve it:
```ts
result.part // part doesn't exist, of course
```

So can you export ParserResult so I can *Merge* the interface with my custom ParserResult? Otherwise, I have to redeclare the entire interface

**Comment by clement-escolano** [comment]
Hello Luca,
Good idea. Indeed, adding a handler does not work well with TypeScript for now. I will do it this week and will notify you when it's done.

**Comment by lucafaggianelli** [comment]
That's great! Thank you

**Comment by clement-escolano** [comment]
Hi Luca.
I have not used TypeScript for a long time and I could not make this work.
I tried to add:
```ts
    export interface ParserResult { }
```
inside this block:

https://github.com/clement-escolano/parse-torrent-title/blob/c00cf45ed8c0c8de02a595d488d91c75013a13ee/index.d.ts#L61-L67

However, in a test project, I could not override `ParserResult` interface and make the `part` property appear in the results.

Do you have any idea on how would you do it? A pull request would be awesome of course.

Cheers

**Comment by lucafaggianelli** [comment]
Hey Clément, I'm quite a beginner with TS, but I think I found a way to make it work

**Comment by clement-escolano** [comment]
Cool! Do you need a modification of the package to make it work? Or did you find a solution which works now?

**Comment by lucafaggianelli** [comment]
I somehow did it. On `parse-torrent-title` package it's just a matter of exporting `ParserResult`, while on the app you must *Augment* the interface, see here on SO:

https://stackoverflow.com/a/52637469/1014873

In the end, there's not much work on the app-side but probably there's a better way to implement this, in particular, I don't like the cast :sob:. Anyway, I created a pull request #15 so you can check the actual changes.

**Comment by clement-escolano** [comment]
Thank you for your example. Indeed, the cast should be avoided as it adds overhead and boilerplate to the developer experience.
I think I have an idea on how to to it nicely with generics. I will check and will tell you how it goes.

**Comment by clement-escolano** [comment]
OK so I have published a new version of the package which should fix the error.
I added documentation on how to use it in the README. Does it works for you?

**Comment by lucafaggianelli** [comment]
Thank you, it works perfectly and it's much better than the cast solution!

**Comment by clement-escolano** [comment]
Perfect :-) Have a good day
