### ISSUE TITLE
still maintained? 

### ISSUE THREAD

**Issue by angelxmoreno** [clement-escolano/parse-torrent-title#16]
@clement-escolano is this repo still maintained? Do you need help?

**Comment by clement-escolano** [comment]
Hello :-)

Thank you for your interest in the project. I am still here but right now, the module work as is and is extensible enough to be used in all kind of projects. The defaults could be improved of course (as indicate the remaining issues) but as it works well enough, I am willing to review pull requests but do not want to spend time coding on it.

If you want to contribue by improving the defaults, this will be greatly appreciated!

Have a good day
