### ISSUE TITLE
bad season

### ISSUE THREAD

**Issue by angelxmoreno** [clement-escolano/parse-torrent-title#17]
for 
`My Adventures with Superman - 1xAll - Complete (Season 720p .mkv WEB)`

I get:
```
resolution: "720p",
container: "mkv",
season: 72,
title: "My Adventures with Superman - 1xAll - Complete"

```

**Comment by clement-escolano** [comment]
I think the best way to fix it would be to add `1xAll` as a season handler (with 1 being a generic number) to catch this scheme :-) Would you be interested in adding a pull request?

**Comment by angelxmoreno** [comment]
why yes, yes I would 👍

**Comment by angelxmoreno** [comment]
done! handlers do indeed make this lib super extensible
