### ISSUE TITLE
Check with another repository

### ISSUE THREAD

**Issue by jy95** [clement-escolano/parse-torrent-title#2]
Hello,

Nice work. I have forked a repository that have the same purpuse as you : it is https://github.com/jy95/torrent-name-parser

Here is the docs I build about their result : https://jy95.github.io/torrent-files-library/TorrentLibrary.html#~TPN

I think you have an more clean project than their but their version seems to have  some good regex  ... 

Can you check this ? Maybe You will find something useful there ^^
Thanks

HS: (You can find there examples of my lib using "parse torrent name" module : https://jy95.github.io/torrent-files-library/index.html , so I wonder your module will be a better choice or not ... )

**Comment by clement-escolano** [comment]
Hello @jy95 
This is funny that you say this because the repo you mentionned was of great inspiration for this project.
Do you have any example of a file name where the other repo is better than mine ? I will be glad to improve my project, it has not been updated for a long time now :) 
Anyway, both projects are pretty similar in my opinion.
Cheers
PS (because HS is only for French speakers 😇 ) : nice project of yours by the way :)

**Comment by jy95** [comment]
For example, the old one has [episodeName extractor](https://github.com/jy95/torrent-name-parser/blob/master/test.js#L73) ( [inside the common part](https://github.com/jy95/torrent-name-parser/blob/master/parts/common.js#L144) ).


PS: There is also an website extractor but I didn't think It is useful for common usage ... Forget this one

**Comment by clement-escolano** [comment]
@jy95 Indeed, the episode name is missing. I had a hard time working on it and it was not so useful for me, so I gave up. I will look again for it. What logic do you think is best for episode name detection ?
After the episode number, if it is not resolution/source ?

**Comment by jy95** [comment]
Yes, if I refer to their tests, it is always after the season episode. The resolution/source generally follows the episode name.

**Comment by clement-escolano** [comment]
Alright then. I will look into it but not immediately.

**Comment by jy95** [comment]
thanks ; hope it will not give you headache  ^^

**Comment by jy95** [comment]
an gift to help you - their test rewritten with chai : https://gist.github.com/jy95/7ce81c77a0673fe4f723abccdcc84073

**Comment by clement-escolano** [comment]
Thanks !

**Comment by jy95** [comment]
I added some news features , new rewritten [docs](https://jy95.github.io/torrent-files-library/) and a [manual ](https://jy95.github.io/torrent-files-library/manual/index.html) to my current lib : `torrent-files-library` : it now allows a custom parser (as explained in your  `Advanced usage` section or the original `torrent-name-parser` project) and custom filtering stuff.
It should handle the types you are using for result : `boolean`, `integer` and `string`.

[Custom parser in constructor](https://jy95.github.io/torrent-files-library/class/src/TorrentLibrary.js~TorrentLibrary.html#instance-constructor-constructor)
[search parameters object for filter functions](https://jy95.github.io/torrent-files-library/typedef/index.html#static-typedef-searchParameters)
[Some examples for filterMovies function tests](https://jy95.github.io/torrent-files-library/test-file/test/methods/filterMovies.js.html)
[Some examples for filterTvSeries function tests](https://jy95.github.io/torrent-files-library/test-file/test/methods/filterTvSeries.js.html)

What do you think about the docs and new features ?

**Comment by clement-escolano** [comment]
Hello!
Sorry for the delay, I have a new job and it takes a lot of time.
The new docs seems pretty clear and the features really neat! One remark: not to create some advertisement for my package but I think a link to this repo when you talk about the custom parser will be useful for those who want to use it ;)

**Comment by jy95** [comment]
No problemo and this is already done : [custom parser](https://github.com/jy95/mediaScan#which-naming-convention-can-i-use-with-this-lib-).

**Comment by clement-escolano** [comment]
Ah indeed I think people will notice better in the README but I was thinking about your docs on the custom parser [here](https://jy95.github.io/torrent-files-library/class/src/TorrentLibrary.js%7ETorrentLibrary.html#instance-constructor-constructor).
